"""add data-driven agent and agent run tables

Revision ID: 0fb63ef4150f
Revises: a23fe3a8267a
Create Date: 2026-08-22 19:30:13.389069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fb63ef4150f"
down_revision: Union[str, None] = "a23fe3a8267a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("destination_id", sa.Integer(), nullable=False),
        sa.Column("mapping_id", sa.Integer(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("actions", sa.Text(), nullable=False),
        sa.Column("feature_notes", sa.JSON(), nullable=False),
        sa.Column("llm_model", sa.String(length=255), nullable=False),
        sa.Column("selection_strategy", sa.String(length=20), nullable=False),
        sa.Column("selection_threshold", sa.Float(), nullable=False),
        sa.Column("incremental_field", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("plan_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["destinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["mapping_id"], ["mappings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_agents_destination_id"),
        "data_agents",
        ["destination_id"],
        unique=False,
    )
    op.create_index(op.f("ix_data_agents_id"), "data_agents", ["id"], unique=False)
    op.create_index(
        op.f("ix_data_agents_mapping_id"), "data_agents", ["mapping_id"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_considered", sa.Integer(), nullable=False),
        sa.Column("rows_selected", sa.Integer(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("selection_summary", sa.Text(), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["data_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_runs_agent_id"), "agent_runs", ["agent_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_id"), "agent_runs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_data_agents_mapping_id"), table_name="data_agents")
    op.drop_index(op.f("ix_data_agents_id"), table_name="data_agents")
    op.drop_index(op.f("ix_data_agents_destination_id"), table_name="data_agents")
    op.drop_table("data_agents")
    # ### end Alembic commands ###
