"""add agent annotation field, run row details, and chat messages

Revision ID: 4bac1ee40993
Revises: 0fb63ef4150f
Create Date: 2026-08-22 20:21:27.949182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bac1ee40993"
down_revision: Union[str, None] = "0fb63ef4150f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["data_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_messages_agent_id"), "agent_messages", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_messages_id"), "agent_messages", ["id"], unique=False
    )
    # server_default lets existing agent_runs rows satisfy NOT NULL; dropped
    # right after since the ORM always supplies row_details on new inserts.
    op.add_column(
        "agent_runs",
        sa.Column("row_details", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.alter_column("agent_runs", "row_details", server_default=None)
    op.add_column(
        "data_agents",
        sa.Column("annotation_field", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_agents", "annotation_field")
    op.drop_column("agent_runs", "row_details")
    op.drop_index(op.f("ix_agent_messages_id"), table_name="agent_messages")
    op.drop_index(op.f("ix_agent_messages_agent_id"), table_name="agent_messages")
    op.drop_table("agent_messages")
    # ### end Alembic commands ###
