"""add sync runs, app settings, advanced connector params

Revision ID: 54397f569e1c
Revises: 7c7c3927e37b
Create Date: 2026-08-19 11:43:02.589582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54397f569e1c"
down_revision: Union[str, None] = "7c7c3927e37b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheduler_enabled", sa.Boolean(), nullable=False),
        sa.Column("scheduler_poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("llm_enabled", sa.Boolean(), nullable=False),
        sa.Column("llm_base_url", sa.String(length=500), nullable=False),
        sa.Column("llm_model", sa.String(length=255), nullable=False),
        sa.Column("default_connect_timeout_seconds", sa.Float(), nullable=False),
        sa.Column("default_request_timeout_seconds", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_read", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["sync_id"], ["syncs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_runs_id"), "sync_runs", ["id"], unique=False)
    op.create_index(
        op.f("ix_sync_runs_sync_id"), "sync_runs", ["sync_id"], unique=False
    )
    op.add_column(
        "destinations", sa.Column("request_timeout", sa.Float(), nullable=True)
    )
    op.add_column("sources", sa.Column("connect_timeout", sa.Float(), nullable=True))
    op.add_column("sources", sa.Column("command_timeout", sa.Float(), nullable=True))
    op.add_column("sources", sa.Column("min_pool_size", sa.Integer(), nullable=True))
    op.add_column("sources", sa.Column("max_pool_size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "max_pool_size")
    op.drop_column("sources", "min_pool_size")
    op.drop_column("sources", "command_timeout")
    op.drop_column("sources", "connect_timeout")
    op.drop_column("destinations", "request_timeout")
    op.drop_index(op.f("ix_sync_runs_sync_id"), table_name="sync_runs")
    op.drop_index(op.f("ix_sync_runs_id"), table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
