"""hours/days interval scheduling and telegram settings

Revision ID: a23fe3a8267a
Revises: 54397f569e1c
Create Date: 2026-08-19 15:52:20.499588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23fe3a8267a'
down_revision: Union[str, None] = '54397f569e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is needed on the two NOT NULL adds below so existing
    # rows (app_settings' singleton row, any pre-existing syncs) get a
    # value instead of failing the migration; dropped again right after
    # since the ORM already supplies these defaults on new inserts.
    op.add_column(
        'app_settings',
        sa.Column('telegram_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'app_settings',
        sa.Column('telegram_bot_token', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'app_settings',
        sa.Column('telegram_chat_id', sa.String(length=255), nullable=False, server_default=''),
    )
    op.alter_column('app_settings', 'telegram_enabled', server_default=None)
    op.alter_column('app_settings', 'telegram_bot_token', server_default=None)
    op.alter_column('app_settings', 'telegram_chat_id', server_default=None)

    op.add_column(
        'syncs',
        sa.Column('interval_value', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'syncs',
        sa.Column('interval_unit', sa.String(length=10), nullable=False, server_default='hours'),
    )
    op.add_column('syncs', sa.Column('run_at_time', sa.String(length=5), nullable=True))
    op.alter_column('syncs', 'interval_value', server_default=None)
    op.alter_column('syncs', 'interval_unit', server_default=None)
    op.drop_column('syncs', 'schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syncs', sa.Column('schedule', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('syncs', 'run_at_time')
    op.drop_column('syncs', 'interval_unit')
    op.drop_column('syncs', 'interval_value')
    op.drop_column('app_settings', 'telegram_chat_id')
    op.drop_column('app_settings', 'telegram_bot_token')
    op.drop_column('app_settings', 'telegram_enabled')
    # ### end Alembic commands ###
